name: CI

on: [push, pull_request, pull_request_review]

jobs:
  build_test:
    strategy:
      matrix:
        env:  # Using some early-adapter applications
          - {ROS_DISTRO: melodic, UPSTREAM_WORKSPACE: .ci/test.repos}
          - {ROS_DISTRO: noetic, UPSTREAM_WORKSPACE: .ci/test.repos}
          - {ROS_DISTRO: melodic, UPSTREAM_WORKSPACE: .ci/test.repos}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
